script_dir = fileparts(mfilename('fullpath'));
project_root = fileparts(fileparts(script_dir));
model_file = fullfile(project_root, 'model', 'ecc_memory_subsystem.slx');
model_name = 'ecc_memory_subsystem';

load_system(model_file);

try
    lines = find_system(model_name, 'FindAll', 'on', 'SearchDepth', 1, 'Type', 'line');
    for line_index = 1:numel(lines)
        try
            delete_line(lines(line_index));
        catch
        end
    end

    delete_workspace_blocks = find_system(model_name, 'SearchDepth', 1, 'BlockType', 'FromWorkspace');
    for block_index = 1:numel(delete_workspace_blocks)
        delete_block(delete_workspace_blocks{block_index});
    end

    rename_block_if_exists(model_name, 'anomaly', 'sample_value');
    rename_block_if_exists(model_name, 'y_ref', 'reference_level');
    delete_block_if_exists(model_name, 'X_ref');
    delete_block_if_exists(model_name, 'ecc_status');
    delete_block_if_exists(model_name, 'Constant');
    delete_block_if_exists(model_name, 'Error_Selector');
    delete_block_if_exists(model_name, 'Product');

    rename_block_if_exists(model_name, 'MATLAB Function', 'ECC_Encoder');
    rename_block_if_exists(model_name, 'MATLAB Function1', 'ECC_Decoder');
    rename_block_if_exists(model_name, 'MATLAB Function2', 'DualPathLogger');
    rename_block_if_exists(model_name, 'MemoryEroorModel', 'MemoryErrorModel');

    add_block_if_missing('simulink/Ports & Subsystems/In1', model_name, 'payload_crc_in', [30 65 60 85]);
    add_block_if_missing('simulink/Ports & Subsystems/In1', model_name, 'error_mode', [30 115 60 135]);
    add_block_if_missing('simulink/Ports & Subsystems/Out1', model_name, 'ecc_corrected', [1050 385 1080 405]);
    add_block_if_missing('simulink/Ports & Subsystems/Out1', model_name, 'snapshot_ecc_words', [1050 435 1080 455]);
    add_block_if_missing('simulink/Math Operations/Abs', model_name, 'Abs_Reference', [175 250 205 280]);
    add_block_if_missing('simulink/User-Defined Functions/MATLAB Function', model_name, 'ECC_Status', [700 140 790 195]);

    set_param([model_name '/payload_crc_in'], 'PortDimensions', '48', 'OutDataTypeStr', 'double');
    set_param([model_name '/error_mode'], 'PortDimensions', '1', 'OutDataTypeStr', 'uint8');
    set_param([model_name '/sample_value'], 'PortDimensions', '1', 'OutDataTypeStr', 'double');
    set_param([model_name '/reference_level'], 'PortDimensions', '1', 'OutDataTypeStr', 'double');
    set_param([model_name '/snapshot_trigger'], 'PortDimensions', '1', 'OutDataTypeStr', 'boolean');
    set_param([model_name '/pathA_out'], 'PortDimensions', '48');
    set_param([model_name '/pathB_out'], 'PortDimensions', '[512 48]');
    set_param([model_name '/snapshot_ecc_words'], 'PortDimensions', '[512 55]');
    set_param([model_name '/Sum'], 'Inputs', '+-');
    set_param([model_name '/Gain'], 'Gain', '0.3');
    set_param([model_name '/Relational Operator'], 'Operator', '>');
    set_param([model_name '/MemoryErrorModel/Logical Operator'], 'Operator', 'XOR');
    set_param([model_name '/MemoryErrorModel'], 'Position', [345 60 455 125]);
    set_param([model_name '/ECC_Encoder'], 'Position', [165 65 250 105]);
    set_param([model_name '/ECC_Decoder'], 'Position', [535 65 625 125]);
    set_param([model_name '/ECC_Status'], 'Position', [700 140 790 195]);
    set_param([model_name '/DualPathLogger'], 'Position', [820 65 930 145]);
    set_param([model_name '/Chart'], 'Position', [700 265 820 365]);
    set_param([model_name '/Sum'], 'Position', [165 190 195 230]);
    set_param([model_name '/Abs'], 'Position', [255 190 285 230]);
    set_param([model_name '/Abs_Reference'], 'Position', [165 255 195 285]);
    set_param([model_name '/Gain'], 'Position', [255 255 305 285]);
    set_param([model_name '/Relational Operator'], 'Position', [375 205 415 245]);
    set_param([model_name '/Scope'], 'Position', [535 420 700 500]);

    encoder_script = strjoin({ ...
        'function code_word = fcn(data_in)', ...
        '%#codegen', ...
        'parity_positions = [1 2 4 8 16 32];', ...
        'data_positions = setdiff(1:54, parity_positions);', ...
        'code_word = zeros(1, 55);', ...
        'for data_index = 1:48', ...
        '    code_word(data_positions(data_index)) = mod(double(data_in(data_index)), 2);', ...
        'end', ...
        'for parity_index = 1:6', ...
        '    parity_position = parity_positions(parity_index);', ...
        '    parity_value = 0;', ...
        '    for bit_position = 1:54', ...
        '        if bitand(uint32(bit_position), uint32(parity_position)) ~= 0', ...
        '            parity_value = mod(parity_value + code_word(bit_position), 2);', ...
        '        end', ...
        '    end', ...
        '    code_word(parity_position) = parity_value;', ...
        'end', ...
        'code_word(55) = mod(sum(code_word(1:54)), 2);', ...
        'end'}, newline);

    decoder_script = strjoin({ ...
        'function [data_out, ecc_corrected, ecc_uncorrectable] = fcn(received_word)', ...
        '%#codegen', ...
        'parity_positions = [1 2 4 8 16 32];', ...
        'data_positions = setdiff(1:54, parity_positions);', ...
        'r = reshape(double(received_word), 1, 55);', ...
        'syndrome = 0;', ...
        'for parity_index = 1:6', ...
        '    parity_position = parity_positions(parity_index);', ...
        '    parity_value = 0;', ...
        '    for bit_position = 1:54', ...
        '        if bitand(uint32(bit_position), uint32(parity_position)) ~= 0', ...
        '            parity_value = mod(parity_value + r(bit_position), 2);', ...
        '        end', ...
        '    end', ...
        '    if parity_value ~= 0', ...
        '        syndrome = syndrome + parity_position;', ...
        '    end', ...
        'end', ...
        'overall_error = mod(sum(r), 2) ~= 0;', ...
        'ecc_corrected = 0;', ...
        'ecc_uncorrectable = 0;', ...
        'if syndrome == 0 && overall_error', ...
        '    r(55) = 1 - r(55);', ...
        '    ecc_corrected = 1;', ...
        'elseif syndrome ~= 0 && overall_error && syndrome <= 54', ...
        '    r(syndrome) = 1 - r(syndrome);', ...
        '    ecc_corrected = 1;', ...
        'elseif syndrome ~= 0 && ~overall_error', ...
        '    ecc_uncorrectable = 1;', ...
        'end', ...
        'data_out = zeros(1, 48);', ...
        'if ecc_uncorrectable == 0', ...
        '    data_out = r(data_positions);', ...
        'end', ...
        'end'}, newline);

    error_mask_script = strjoin({ ...
        'function error_mask = fcn(error_mode)', ...
        '%#codegen', ...
        'error_mask = zeros(1, 55);', ...
        'if error_mode == 1', ...
        '    error_mask(5) = 1;', ...
        'elseif error_mode == 2', ...
        '    error_mask(5) = 1;', ...
        '    error_mask(12) = 1;', ...
        'end', ...
        'end'}, newline);

    logger_script = strjoin({ ...
        'function [pathA_out, pathB_out, snapshot_ready, snapshot_ecc_words] = fcn(ecc_data, ecc_word, snapshot_trigger, log_enable)', ...
        '%#codegen', ...
        'persistent ring_buffer ring_codewords write_index valid_count snapshot_buffer snapshot_codewords recording post_count previous_trigger', ...
        'if isempty(ring_buffer)', ...
        '    ring_buffer = zeros(512, 48);', ...
        '    ring_codewords = zeros(512, 55);', ...
        '    write_index = 1;', ...
        '    valid_count = 0;', ...
        '    snapshot_buffer = zeros(512, 48);', ...
        '    snapshot_codewords = zeros(512, 55);', ...
        '    recording = false;', ...
        '    post_count = 0;', ...
        '    previous_trigger = false;', ...
        'end', ...
        'snapshot_ready = false;', ...
        'trigger_active = snapshot_trigger ~= 0;', ...
        'if log_enable', ...
        '    if trigger_active && ~previous_trigger && ~recording', ...
        '        snapshot_buffer = zeros(512, 48);', ...
        '        snapshot_codewords = zeros(512, 55);', ...
        '        pre_count = min(valid_count, 256);', ...
        '        for index = 1:pre_count', ...
        '            source_index = mod(write_index - pre_count + index - 2, 512) + 1;', ...
        '            destination_index = 257 - pre_count + index - 1;', ...
        '            snapshot_buffer(destination_index, :) = ring_buffer(source_index, :);', ...
        '            snapshot_codewords(destination_index, :) = ring_codewords(source_index, :);', ...
        '        end', ...
        '        snapshot_buffer(257, :) = ecc_data;', ...
        '        snapshot_codewords(257, :) = ecc_word;', ...
        '        recording = true;', ...
        '        post_count = 1;', ...
        '    elseif recording', ...
        '        if post_count < 256', ...
        '            post_count = post_count + 1;', ...
        '            snapshot_buffer(256 + post_count, :) = ecc_data;', ...
        '            snapshot_codewords(256 + post_count, :) = ecc_word;', ...
        '        end', ...
        '        if post_count == 256', ...
        '            recording = false;', ...
        '            snapshot_ready = true;', ...
        '        end', ...
        '    end', ...
        '    ring_buffer(write_index, :) = ecc_data;', ...
        '    ring_codewords(write_index, :) = ecc_word;', ...
        '    write_index = mod(write_index, 512) + 1;', ...
        '    valid_count = min(valid_count + 1, 512);', ...
        'end', ...
        'previous_trigger = trigger_active;', ...
        'pathA_out = zeros(1, 48);', ...
        'if log_enable', ...
        '    pathA_out = ecc_data;', ...
        'end', ...
        'pathB_out = snapshot_buffer;', ...
        'snapshot_ecc_words = snapshot_codewords;', ...
        'end'}, newline);

    status_script = strjoin({ ...
        'function status = fcn(ecc_corrected, ecc_uncorrectable)', ...
        '%#codegen', ...
        'status = uint8(0);', ...
        'if ecc_uncorrectable ~= 0', ...
        '    status = uint8(2);', ...
        'elseif ecc_corrected ~= 0', ...
        '    status = uint8(1);', ...
        'end', ...
        'end'}, newline);

    set_emchart_script(model_name, 'ECC_Encoder', encoder_script);
    set_emchart_script(model_name, 'ECC_Decoder', decoder_script);
    set_emchart_script([model_name '/MemoryErrorModel'], 'MATLAB Function', error_mask_script);
    set_emchart_script(model_name, 'DualPathLogger', logger_script);
    set_emchart_script(model_name, 'ECC_Status', status_script);
    set_emchart_data_size(model_name, 'ECC_Encoder', 'data_in', '[1 48]');
    set_emchart_data_size(model_name, 'ECC_Encoder', 'code_word', '[1 55]');
    set_emchart_data_size(model_name, 'ECC_Decoder', 'received_word', '[1 55]');
    set_emchart_data_size(model_name, 'ECC_Decoder', 'data_out', '[1 48]');
    set_emchart_data_size([model_name '/MemoryErrorModel'], 'MATLAB Function', 'error_mask', '[1 55]');
    set_emchart_data_size(model_name, 'DualPathLogger', 'ecc_data', '[1 48]');
    set_emchart_data_size(model_name, 'DualPathLogger', 'ecc_word', '[1 55]');
    set_emchart_data_size(model_name, 'DualPathLogger', 'pathA_out', '[1 48]');
    set_emchart_data_size(model_name, 'DualPathLogger', 'pathB_out', '[512 48]');
    set_emchart_data_size(model_name, 'DualPathLogger', 'snapshot_ecc_words', '[512 55]');

    chart = get_stateflow_chart(model_name, 'Chart');
    chart_data = chart.find('-isa', 'Stateflow.Data');
    for data_index = 1:numel(chart_data)
        switch chart_data(data_index).Name
            case 'anomaly'
                chart_data(data_index).Props.Array.Size = '1';
                chart_data(data_index).DataType = 'boolean';
            case 'ecc_status'
                chart_data(data_index).Props.Array.Size = '1';
                chart_data(data_index).DataType = 'uint8';
            case {'error_alarm', 'write_enable'}
                chart_data(data_index).DataType = 'boolean';
            case 'system_state'
                chart_data(data_index).DataType = 'uint8';
        end
    end

    states = chart.find('-isa', 'Stateflow.State');
    for state_index = 1:numel(states)
        switch states(state_index).Name
            case 'Normal'
                states(state_index).LabelString = sprintf('Normal\nentry:\nwrite_enable = true;\nerror_alarm = false;\nsystem_state = 1;');
            case 'Error'
                states(state_index).LabelString = sprintf('Error\nentry:\nwrite_enable = false;\nerror_alarm = true;\nsystem_state = 5;');
        end
    end

    add_line(model_name, 'payload_crc_in/1', 'ECC_Encoder/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Encoder/1', 'MemoryErrorModel/1', 'autorouting', 'on');
    add_line(model_name, 'error_mode/1', 'MemoryErrorModel/2', 'autorouting', 'on');
    add_line(model_name, 'MemoryErrorModel/1', 'ECC_Decoder/1', 'autorouting', 'on');
    add_line(model_name, 'MemoryErrorModel/1', 'DualPathLogger/2', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/1', 'data_out/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/1', 'DualPathLogger/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/1', 'Scope/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/2', 'ecc_corrected/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/2', 'ECC_Status/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/2', 'Scope/2', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/3', 'ecc_uncorrectable/1', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/3', 'ECC_Status/2', 'autorouting', 'on');
    add_line(model_name, 'ECC_Decoder/3', 'Scope/3', 'autorouting', 'on');

    ecc_status_port = stateflow_data_port(chart, 'ecc_status');
    anomaly_port = stateflow_data_port(chart, 'anomaly');
    add_line(model_name, 'ECC_Status/1', ['Chart/' num2str(ecc_status_port)], 'autorouting', 'on');
    add_line(model_name, 'Relational Operator/1', ['Chart/' num2str(anomaly_port)], 'autorouting', 'on');

    add_line(model_name, 'sample_value/1', 'Sum/1', 'autorouting', 'on');
    add_line(model_name, 'reference_level/1', 'Sum/2', 'autorouting', 'on');
    add_line(model_name, 'reference_level/1', 'Abs_Reference/1', 'autorouting', 'on');
    add_line(model_name, 'Sum/1', 'Abs/1', 'autorouting', 'on');
    add_line(model_name, 'Abs/1', 'Relational Operator/1', 'autorouting', 'on');
    add_line(model_name, 'Abs_Reference/1', 'Gain/1', 'autorouting', 'on');
    add_line(model_name, 'Gain/1', 'Relational Operator/2', 'autorouting', 'on');

    add_line(model_name, 'snapshot_trigger/1', 'DualPathLogger/3', 'autorouting', 'on');
    add_line(model_name, 'Chart/2', 'DualPathLogger/4', 'autorouting', 'on');
    add_line(model_name, 'DualPathLogger/1', 'pathA_out/1', 'autorouting', 'on');
    add_line(model_name, 'DualPathLogger/2', 'pathB_out/1', 'autorouting', 'on');
    add_line(model_name, 'DualPathLogger/3', 'snapshot_ready/1', 'autorouting', 'on');
    add_line(model_name, 'DualPathLogger/4', 'snapshot_ecc_words/1', 'autorouting', 'on');
    add_line(model_name, 'Chart/1', 'error_alarm/1', 'autorouting', 'on');
    add_line(model_name, 'Chart/2', 'write_enable/1', 'autorouting', 'on');
    add_line(model_name, 'Chart/3', 'system_state/1', 'autorouting', 'on');

    set_param(model_name, 'Solver', 'FixedStepDiscrete', 'FixedStep', '1', 'StopTime', '600');
    set_param(model_name, 'SimulationCommand', 'update');
    save_system(model_name, model_file);
    close_system(model_name, 0);
    fprintf('Built and updated %s\n', model_file);
catch exception
    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end
    rethrow(exception);
end

function set_emchart_script(model_name, block_name, script)
chart_path = [model_name '/' block_name];
root = sfroot;
charts = root.find('-isa', 'Stateflow.EMChart');
for chart_index = 1:numel(charts)
    if strcmp(charts(chart_index).Path, chart_path)
        charts(chart_index).Script = script;
        return;
    end
end
error('MATLAB Function chart not found: %s', chart_path);
end

function set_emchart_data_size(model_name, block_name, data_name, size_value)
chart_path = [model_name '/' block_name];
root = sfroot;
charts = root.find('-isa', 'Stateflow.EMChart');
for chart_index = 1:numel(charts)
    if strcmp(charts(chart_index).Path, chart_path)
        data = charts(chart_index).find('-isa', 'Stateflow.Data');
        for data_index = 1:numel(data)
            if strcmp(data(data_index).Name, data_name)
                data(data_index).Props.Array.Size = size_value;
                return;
            end
        end
    end
end
error('MATLAB Function data not found: %s/%s', chart_path, data_name);
end

function chart = get_stateflow_chart(model_name, block_name)
chart_path = [model_name '/' block_name];
root = sfroot;
charts = root.find('-isa', 'Stateflow.Chart');
for chart_index = 1:numel(charts)
    if strcmp(charts(chart_index).Path, chart_path)
        chart = charts(chart_index);
        return;
    end
end
error('Stateflow chart not found: %s', chart_path);
end

function port = stateflow_data_port(chart, data_name)
data = chart.find('-isa', 'Stateflow.Data');
for data_index = 1:numel(data)
    if strcmp(data(data_index).Name, data_name)
        port = data(data_index).Port;
        return;
    end
end
error('Stateflow input not found: %s', data_name);
end

function rename_block_if_exists(model_name, old_name, new_name)
old_path = [model_name '/' old_name];
if ~isempty(find_system(model_name, 'SearchDepth', 1, 'Name', old_name))
    if isempty(find_system(model_name, 'SearchDepth', 1, 'Name', new_name))
        set_param(old_path, 'Name', new_name);
    end
end
end

function delete_block_if_exists(model_name, block_name)
if ~isempty(find_system(model_name, 'SearchDepth', 1, 'Name', block_name))
    delete_block([model_name '/' block_name]);
end
end

function add_block_if_missing(library_path, model_name, block_name, position)
if isempty(find_system(model_name, 'SearchDepth', 1, 'Name', block_name))
    add_block(library_path, [model_name '/' block_name], 'Position', position);
end
end